// <auto-generated>
//   由 scripts\build-changelog.ps1 从仓库根目录的 RELEASE_NOTES.md 生成，请勿手动修改。
//   要调整内容，请编辑 RELEASE_NOTES.md，再重新运行该脚本。
// </auto-generated>
namespace ColoringPixelsTool
{
    /// <summary>软件更新公告文本（来源：RELEASE_NOTES.md / VERSION）。</summary>
    internal static class Changelog
    {
        public const string CurrentVersion = "2.3.1";

        public const string Body =
"欢迎回来，Coloring Pixels Tool V2.3.1！\n" +
"\n" +
"这一版没有改任何程序功能 —— 插件、安装器与《涂色大师》助手和 V2.3.0 完全一致，\n" +
"可以不必更新。变的是仓库里的开发文档：\n" +
"\n" +
"· 开发心路历程 的时间线补齐了 2.2.2 ~ 2.3.0 共 11 个版本；\n" +
"· 新增「第九章 · 那些『看起来在工作』的功能」，记录了速度预设被每帧覆盖、\n" +
"  经验值保底导致实际快 30 倍、扫描速度受「一帧只推进一个采样点」限制、\n" +
"  助手「预览」页的构建函数压根没被调用这几处「界面正常、按钮能点、功能不动」的坑，\n" +
"  以及从它们身上得出的两条结论：把暗中的约定写成显式状态、同一个事实只留一个真源；\n" +
"· 「接下来想做的事」里「格子校准不再依赖人工框选」已经在 2.2.5 与 2.3.0 实现，标记完成。\n" +
"\n" +
"想知道 V2.3.0 加了什么（助手补齐预览页与各页功能、两款游戏共用等级存档），\n" +
"请看 CHANGELOG 或对应的 Release 说明。";
    }
}
