// <auto-generated>
//   由 scripts\build-changelog.ps1 从仓库根目录的 RELEASE_NOTES.md 生成，请勿手动修改。
//   要调整内容，请编辑 RELEASE_NOTES.md，再重新运行该脚本。
// </auto-generated>
namespace ColoringPixelsTool
{
    /// <summary>软件更新公告文本（来源：RELEASE_NOTES.md / VERSION）。</summary>
    internal static class Changelog
    {
        public const string CurrentVersion = "2.3.8";

        public const string Body =
"欢迎回来，Coloring Pixels Tool V2.3.8！\n" +
"\n" +
"这次专门收拾「面板调不出来」这件事——原因有两处，一并修掉了。\n" +
"\n" +
"修复：弹窗压住面板、热键又把面板一起关掉\n" +
"\n" +
"· 首次启动会弹「功能总览 / 新手指引」，之前它们画在面板上面并独占整屏交互：\n" +
"  面板其实已经画出来了，却被一整层遮罩盖着、点不动，看起来就像「面板根本没出现」。\n" +
"· 现在弹窗改到面板下面绘制，面板永远压在最上层、始终完整可见可点；\n" +
"  弹窗卡片会主动让到面板右侧，两者互不遮挡。\n" +
"· 面板热键（默认 F1）的语义改成「把面板调出来」：只要还压着弹窗，按下热键就先把弹窗收掉、\n" +
"  并把面板显示出来，而不是连面板一起关掉。Esc 也能直接关掉当前弹窗。\n" +
"\n" +
"修复：某一处绘制出错导致整个面板消失\n" +
"\n" +
"· 面板、HUD、公告等以前共用同一次 OnGUI，任何一处抛异常都会把后面的绘制整块带崩，\n" +
"  表现同样是「按 F1 没反应」。现在每一段单独兜错，互不影响；\n" +
"  万一真的出错，只会在日志里记一条并标明是哪一段，不再连累其它界面。";
    }
}
