#Requires -Version 5.1
<#
    编译单文件安装器 ColoringPixelsTool-Setup.exe。

    优先使用系统自带的 .NET Framework csc.exe（无需安装 .NET SDK）；
    如果找不到 csc，则回退到 dotnet build。

    产物：dist\ColoringPixelsTool-Setup-v<版本>.exe
#>
[CmdletBinding()]
param(
    [string]$Version,
    [string]$Output,
    [string]$PayloadZip,
    [switch]$SkipIcon
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($Output)) { $Output = Join-Path $repoRoot 'dist' }
if ([string]::IsNullOrWhiteSpace($PayloadZip)) { $PayloadZip = Join-Path $repoRoot 'build\payload.zip' }

function Step($m) { Write-Host "  >> $m" -ForegroundColor Cyan }
function Ok($m) { Write-Host "  OK $m" -ForegroundColor Green }
function Warn($m) { Write-Host "  !! $m" -ForegroundColor Yellow }
function Fail($m) { Write-Host "  XX $m" -ForegroundColor Red; throw $m }

function Resolve-Version {
    param([string]$Explicit)

    if (-not [string]::IsNullOrWhiteSpace($Explicit)) {
        return $Explicit.Trim().TrimStart('v', 'V')
    }

    $versionFile = Join-Path $repoRoot 'VERSION'
    if (Test-Path -LiteralPath $versionFile) {
        return (Get-Content -LiteralPath $versionFile -Raw).Trim().TrimStart('v', 'V')
    }

    return '1.0.0'
}

function Get-RepoUrl {
    $props = Join-Path $repoRoot 'Directory.Build.props'
    if (Test-Path -LiteralPath $props) {
        $m = [regex]::Match((Get-Content -LiteralPath $props -Raw), '<RepositoryUrl>\s*([^<]+?)\s*</RepositoryUrl>')
        if ($m.Success) { return $m.Groups[1].Value }
    }
    return 'https://github.com/zlwzk/ColoringPixels-Tool'
}

function New-FourPartVersion {
    param([string]$Value)

    $parts = @($Value.Split('.') | Where-Object { $_ -ne '' })
    while ($parts.Count -lt 4) { $parts += '0' }
    return ($parts[0..3] -join '.')
}

# ---------------------------------------------------------------- 0. 基本信息

$version = Resolve-Version -Explicit $Version
$repoUrl = Get-RepoUrl
$builtAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$fourPart = New-FourPartVersion -Value $version

Write-Host ''
Write-Host "  版本：$version" -ForegroundColor White
Write-Host "  仓库：$repoUrl" -ForegroundColor DarkGray
Write-Host ''

# ---------------------------------------------------------------- 1. payload

if (-not (Test-Path -LiteralPath $PayloadZip)) {
    Warn "未找到 $PayloadZip，先执行 build-payload.ps1"
    & (Join-Path $PSScriptRoot 'build-payload.ps1') -Output (Split-Path -Parent $PayloadZip)
}

if (-not (Test-Path -LiteralPath $PayloadZip)) { Fail "缺少部署包：$PayloadZip" }
Ok ("部署包：{0} ({1:N0} KB)" -f $PayloadZip, ((Get-Item -LiteralPath $PayloadZip).Length / 1KB))

# ---------------------------------------------------------------- 2. 图标

$icon = Join-Path $repoRoot 'assets\icon.ico'
if (-not $SkipIcon -and -not (Test-Path -LiteralPath $icon)) {
    Step '生成应用图标……'
    & (Join-Path $PSScriptRoot 'make-icon.ps1') -Output $icon
}
$hasIcon = Test-Path -LiteralPath $icon

# ---------------------------------------------------------------- 3. 生成版本信息

$genDir = Join-Path $repoRoot 'installer\obj\gen'
if (-not (Test-Path -LiteralPath $genDir)) { New-Item -ItemType Directory -Path $genDir -Force | Out-Null }
$genFile = Join-Path $genDir 'AssemblyInfo.g.cs'

$assemblyInfo = @"
// <auto-generated>
//   由 scripts\build-installer.ps1 生成，请勿手动修改。
// </auto-generated>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Coloring Pixels Tool Installer")]
[assembly: AssemblyDescription("Coloring Pixels 作弊套件的一键安装器")]
[assembly: AssemblyProduct("Coloring Pixels Tool")]
[assembly: AssemblyCompany("Coloring Pixels Tool contributors")]
[assembly: AssemblyCopyright("MIT License")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyVersion("$fourPart")]
[assembly: AssemblyFileVersion("$fourPart")]
[assembly: AssemblyInformationalVersion("$version")]
[assembly: ComVisible(false)]
[assembly: AssemblyMetadata("RepositoryUrl", "$repoUrl")]
[assembly: AssemblyMetadata("BuiltAt", "$builtAt")]
"@

[System.IO.File]::WriteAllText($genFile, $assemblyInfo, (New-Object System.Text.UTF8Encoding($true)))
Ok "已生成版本信息：$genFile"

# ---------------------------------------------------------------- 4. 收集源文件

$sources = @(Get-ChildItem -LiteralPath (Join-Path $repoRoot 'installer') -Filter '*.cs' -File | Sort-Object Name | ForEach-Object { $_.FullName })
$sources += $genFile

if ($sources.Count -le 1) { Fail '没有找到 installer\*.cs 源文件' }

if (-not (Test-Path -LiteralPath $Output)) { New-Item -ItemType Directory -Path $Output -Force | Out-Null }
$outExe = Join-Path $Output ("ColoringPixelsTool-Setup-v{0}.exe" -f $version)
if (Test-Path -LiteralPath $outExe) { Remove-Item -LiteralPath $outExe -Force }

# ---------------------------------------------------------------- 5. 编译

function Compile-WithCsc {
    param([string]$Csc)

    $frameworkDir = Split-Path -Parent $Csc
    $parts = New-Object System.Collections.ArrayList

    foreach ($a in @('/nologo', '/target:winexe', '/platform:anycpu', '/optimize+', '/langversion:5',
                     '/warn:4', '/codepage:65001', '/utf8output')) {
        [void]$parts.Add($a)
    }

    [void]$parts.Add(('/out:"{0}"' -f $outExe))
    [void]$parts.Add(('/resource:"{0}",payload.zip' -f $PayloadZip))
    if ($hasIcon) { [void]$parts.Add(('/win32icon:"{0}"' -f $icon)) }

    foreach ($r in @('System.dll', 'System.Core.dll', 'System.Drawing.dll',
                     'System.Windows.Forms.dll', 'System.IO.Compression.dll')) {
        $path = Join-Path $frameworkDir $r
        if (Test-Path -LiteralPath $path) { [void]$parts.Add(('/r:"{0}"' -f $path)) }
    }

    foreach ($s in $sources) { [void]$parts.Add(('"{0}"' -f $s)) }

    $argString = ($parts -join ' ')
    $proc = Start-Process -FilePath $Csc -ArgumentList $argString -Wait -NoNewWindow -PassThru
    return $proc.ExitCode
}

function Compile-WithDotnet {
    $csproj = Join-Path $repoRoot 'installer\ColoringPixelsTool.Installer.csproj'
    if (-not (Test-Path -LiteralPath $csproj)) { Fail '找不到 installer 工程文件，且没有可用的 csc.exe' }

    $work = Join-Path $repoRoot 'build\dotnet-installer'
    if (Test-Path -LiteralPath $work) { Remove-Item -LiteralPath $work -Recurse -Force }

    & dotnet build $csproj -c Release -o $work -p:Version=$version -p:PayloadZip=$PayloadZip --nologo
    if ($LASTEXITCODE -ne 0) { return $LASTEXITCODE }

    $built = Join-Path $work 'ColoringPixelsTool-Setup.exe'
    if (-not (Test-Path -LiteralPath $built)) { Fail "dotnet build 未生成 $built" }
    Copy-Item -LiteralPath $built -Destination $outExe -Force
    return 0
}

$cscCandidates = @(
    (Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'),
    (Join-Path $env:WINDIR 'Microsoft.NET\Framework\v4.0.30319\csc.exe')
)

$csc = $null
foreach ($c in $cscCandidates) {
    if (Test-Path -LiteralPath $c) { $csc = $c; break }
}

if ($null -ne $csc) {
    Step "使用 $csc 编译……"
    $code = Compile-WithCsc -Csc $csc
    if ($code -ne 0) { Fail "csc 编译失败（退出码 $code）" }
}
else {
    $dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
    if ($null -eq $dotnet) {
        Fail '既找不到 csc.exe 也找不到 dotnet，无法编译。请安装 .NET Framework 4.x 或 .NET SDK。'
    }

    Step '未找到 csc.exe，回退到 dotnet build……'
    $code = Compile-WithDotnet
    if ($code -ne 0) { Fail "dotnet build 失败（退出码 $code）" }
}

if (-not (Test-Path -LiteralPath $outExe)) { Fail "编译未产出 $outExe" }

# ---------------------------------------------------------------- 6. 校验内嵌资源

$inner = "([System.Reflection.Assembly]::LoadFile('" + $outExe + "')).GetManifestResourceNames() -join ','"
$names = (& powershell -NoProfile -NonInteractive -Command $inner) -join ''
if ($names -notmatch 'payload\.zip') {
    Fail "安装器内嵌资源校验失败（实际为：$names）"
}

$info = Get-Item -LiteralPath $outExe
Ok ("安装器已生成：{0} ({1:N0} KB)" -f $info.FullName, ($info.Length / 1KB))

$sha = (Get-FileHash -LiteralPath $outExe -Algorithm SHA256).Hash
Write-Host ("     SHA256: {0}" -f $sha) -ForegroundColor DarkGray
