// <auto-generated>
//   由 scripts\build-changelog.ps1 从仓库根目录的 RELEASE_NOTES.md 生成，请勿手动修改。
//   要调整内容，请编辑 RELEASE_NOTES.md，再重新运行该脚本。
// </auto-generated>
namespace ColoringPixelsTool.Installer
{
    /// <summary>安装完成后弹窗的更新公告文本（来源：RELEASE_NOTES.md / VERSION）。</summary>
    internal static class ReleaseNotes
    {
        public const string Version = "3.0.3";

        public const string Body =
"Coloring Pixels Tool V3.0.3\r\n" +
"\r\n" +
"欢迎回来！先说清楚最重要的一句：这一版没有任何玩法改动 —— 面板长什么样、按钮在哪、数据存在哪，\r\n" +
"全都和 V3.0.2 一模一样。它存在的唯一原因，是把「界面数值输入的规矩」固化成了开发规则，\r\n" +
"顺手把整个项目按这条规矩复核了一遍。\r\n" +
"\r\n" +
"📏 新增：界面数值输入的硬规矩\r\n" +
"\r\n" +
"五条规矩，写进了仓库的 .codebuddy/rules/ui-numeric-input：\r\n" +
"\r\n" +
"· 时间 / 百分比 / 次数 / 阈值这类参数，必须用原生数值控件（滑条、数值字段），\r\n" +
"  不许拿普通文本框让人手打数字；\r\n" +
"· 输入框里只放半角阿拉伯数字，不许出现单位、说明文字、全角数字；\r\n" +
"· 单位（秒 / % / 次 / px / MB）一律放在输入框外面当独立标签，不许塞进框里；\r\n" +
"· 不许用 Ⅱ、○、◆ 这类符号当占位文本，默认值直接写有效数字（100、10、0）；\r\n" +
"· 不许把「间隔：200」这种模板文案直接当成输入框的初始值。\r\n" +
"\r\n" +
"✅ 复核结论：本项目本来就合规，界面代码零改动\r\n" +
"\r\n" +
"· 插件面板（IMGUI）里所有数值参数本来就是滑条 + 值域钳制（Slider(...) 统一处理，\r\n" +
"  每个参数都有上下限），不存在「文本框装数值」的情况；\r\n" +
"· 安装器（WinForms）里出现的文本框只有三处：游戏目录路径、安装日志、更新公告正文 ——\r\n" +
"  全是文本，本来就该是文本框，不涉及数值 + 单位混写；\r\n" +
"· 所以本版没有修改任何界面代码，也没有改动任何数值的上下限或默认值。\r\n" +
"\r\n" +
"📦 本版实际改动\r\n" +
"\r\n" +
"· 新增开发规则文件 .codebuddy/rules/ui-numeric-input/RULE.mdc；\r\n" +
"· 版本号 3.0.2 → 3.0.3（插件面板、安装包同步）。\r\n" +
"\r\n" +
"✅ 与 V3.0.2 完全一致的部分\r\n" +
"\r\n" +
"只支持《Coloring Pixels》（Steam AppID 897330，BepInEx 注入，进关卡按 F1 开面板）；\r\n" +
"面板分「自动完成 / 人工辅助」两大模块；两条互不相干的经验线（自动绘图 / 人工辅助）与两套称号；\r\n" +
"双主题（柔光马卡龙 / 深靛霓虹）；提醒页与首次启动功能总览；等级存档落在\r\n" +
"%APPDATA%\\ColoringPixelsTool\\ 并带 .bak 与损坏隔离；退出二次确认；中文字形兜底 —— 全部照旧。\r\n" +
"\r\n" +
"🔄 要升级吗？\r\n" +
"\r\n" +
"玩法体验上和 V3.0.2 没有任何区别，不升级也完全没问题。\r\n" +
"如果你习惯「仓库有新版本就跟着更新」，那升上去就行，安装包会覆盖旧版本，等级与经验值不受影响。\r\n" +
"\r\n" +
"🧹 小提醒\r\n" +
"\r\n" +
"安装/卸载仍会自动清理游戏目录里遗留的 PixelAssist\\ 目录；用户数据始终放在\r\n" +
"%APPDATA%\\ColoringPixelsTool\\，覆盖安装、卸载插件、验证游戏文件都不会带走它。";
    }
}