// <auto-generated>
//   由 scripts\build-changelog.ps1 从仓库根目录的 RELEASE_NOTES.md 生成，请勿手动修改。
//   要调整内容，请编辑 RELEASE_NOTES.md，再重新运行该脚本。
// </auto-generated>
namespace ColoringPixelsTool.Installer
{
    /// <summary>安装完成后弹窗的更新公告文本（来源：RELEASE_NOTES.md / VERSION）。</summary>
    internal static class ReleaseNotes
    {
        public const string Version = "2.3.7";

        public const string Body =
"欢迎回来，Coloring Pixels Tool V2.3.7！\r\n" +
"\r\n" +
"这次修的是「装完之后启动游戏会闪退」——现在交给 Steam 来开机。\r\n" +
"\r\n" +
"修复：安装器直接拉 exe 导致游戏闪退\r\n" +
"\r\n" +
"· 这两款游戏都是在 Steam 上卖的，游戏启动时要靠 Steam 客户端接管 Steamworks。\r\n" +
"  安装器以前是直接 Process.Start 游戏 exe，Steam 没参与，游戏起来几百毫秒就自己退了，\r\n" +
"  用户看到的就是「刚弹出个黑框就没了」，只能再去 Steam 库里手动点一次启动。\r\n" +
"· 现在「启动游戏」和「安装完成后自动启动」都会先走 steam://rungameid/，\r\n" +
"  由 Steam 把游戏正常拉起来。Steam 没开着也没关系，协议会自动叫醒它。\r\n" +
"· 只有确认「这个目录就是 Steam 库里装的这一份」（对得上 appmanifest_.acf）才走 Steam，\r\n" +
"  绿色版 / 非 Steam 版仍然直接启动，不会被丢到商店页干瞪眼。\r\n" +
"\r\n" +
"顺带\r\n" +
"\r\n" +
"· Steam 启动时拿不到游戏进程句柄，所以「游戏打开后自动关闭安装器」改成按进程名轮询，\r\n" +
"  等游戏真的起来再自动关闭（等待上限从 60 秒放宽到 90 秒，Steam 拉起来会慢一截）。\r\n" +
"· 游戏已经在运行时，依然只把窗口切到前台，不会多开一个。";
    }
}
